version: '3.3'
services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - PSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    image: 88228811133000/foodgram:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:

      - django_static_value:/app/django_static/

      - django_media_value:/app/django_media/

    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: 88228811133000/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - django_static_value:/var/html/django_static/

      - django_media_value:/var/html/django_media/
    depends_on:
      - backend

 
volumes:
  db:
  django_static_value:
  django_media_value: 