# Generated by Django 2.2.16 on 2022-12-19 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount of ingredient in receipt')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name of the ingredient')),
                ('minimal_amount', models.IntegerField(verbose_name='minimal amount of ingredient')),
                ('unit', models.CharField(max_length=32, verbose_name='unit of measure')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name of the tag')),
                ('color_code', models.CharField(max_length=7, unique=True, verbose_name='color code of the tag')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title of the receipt')),
                ('image', models.ImageField(upload_to='receipts/', verbose_name='image of the receipt')),
                ('description', models.TextField(verbose_name='text description')),
                ('cooking_time', models.IntegerField(verbose_name='cooking time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='author of the receipt')),
                ('ingredients', models.ManyToManyField(through='receipts.AttachedIngredient', to='receipts.Ingredient')),
                ('tags', models.ManyToManyField(through='receipts.AttachedTag', to='receipts.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='attachedtag',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.Receipt'),
        ),
        migrations.AddField(
            model_name='attachedtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.Tag'),
        ),
        migrations.AddField(
            model_name='attachedingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.Ingredient'),
        ),
        migrations.AddField(
            model_name='attachedingredient',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.Receipt'),
        ),
    ]
