# Generated by Django 2.2.16 on 2022-12-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20221220_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='attachedingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_to_receipts', to='receipts.Ingredient'),
        ),
        migrations.AlterField(
            model_name='attachedingredient',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_ingredients', to='receipts.Receipt'),
        ),
        migrations.AlterField(
            model_name='attachedtag',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_tags', to='receipts.Receipt'),
        ),
        migrations.AlterField(
            model_name='attachedtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_receipts', to='receipts.Tag'),
        ),
    ]
