# Generated by Django 2.2.16 on 2022-12-27 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20221221_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount of ingredient in receipt'),
        ),
        migrations.AlterField(
            model_name='attachedingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attached_to_receipts', to='receipts.Ingredient'),
        ),
    ]
