# Generated by Django 2.2.16 on 2023-01-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id']},
        ),
    ]
